name: "Pull Request Labeler"
on:
- pull_request_target

jobs:
  labeler:
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
    - name: Check Permissions
      run: |
        echo "Testing permissions..."
        echo "Contents permission: ${{ permissions.contents }}"
        echo "Pull-requests permission: ${{ permissions.pull-requests }}"
        echo "Issues permission: ${{ permissions.issues }}"
    - id: label-the-PR
      uses: actions/labeler@v5
      with:
        sync-labels: true
