name: PR Labeler

on:
  pull_request_target:
    types: [opened, synchronize]

jobs:
  label:
    permissions:
      contents: read
      pull-requests: write
    name: Add PR labels
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4
      - id: label-the-PR
        uses: actions/labeler@v5
        with:
          sync-labels: true
